name: lokaverkefni
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.4

# Add regular dependencies here.
dependencies:
     flutter:
         sdk: flutter
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0

flutter:
  uses-material-design: true
  fonts:
    - family: SourceCodePro
      fonts:
        - asset: lib\assets\fonts\SourceCodePro-MediumItalic.ttf
  assets:
    - lib/assets/garf_background.jpg
    - lib/assets/garf_win.png
